[package]
name = "conn_scylla"
version = "0.1.0"
edition = "2021"

[dependencies]
common = {path = "../common"}
conn = {path = "../conn"}
tokio = {version = "1.43.0"}
scylla = "0.15.1"

[[test]]
name = "test_root"
path = "tests/mod.rs"