[collect]
type = "sql"

[collect.sql]
dbtype = 'postgres'
connection = [
     {ip = '127.0.0.1', port=5432, user='postgres', password='postgres', dbname='postgres'}
]

query = 'select 1 as val'
fetch = {'val' = {val_type = 'int'}}

[send]
type = "sql"

[send.sql]
dbtype = 'postgres'
connection = [
     {ip = '127.0.0.1', port=5432, user='postgres', password='postgres', dbname='postgres'}
]
query = 'select #{val}'
